-- =============================================================================
-- 0002_catalogue.sql
-- Products, variants, identifiers, research and opportunity scoring.
-- =============================================================================

-- Product lifecycle (§28). Order matters: the app renders progress from it.
create type product_stage as enum (
  'discovered',
  'researching',
  'supplier_review',
  'compliance_review',
  'approved',
  'testing',
  'proven',
  'scaling',
  'mature',
  'declining',
  'paused',
  'removed'
);

create table products (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references organisations(id) on delete cascade,

  sku         text not null,
  title       text not null,
  slug        citext,
  description text,
  category    text,
  brand       text,

  stage       product_stage not null default 'discovered',
  is_demo     boolean not null default false,

  -- Physical characteristics feed shipping cost and return-risk scoring
  weight_grams int,
  length_mm    int,
  width_mm     int,
  height_mm    int,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  unique (org_id, sku)
);

create index products_org_stage_idx on products(org_id, stage);
create index products_org_demo_idx on products(org_id, is_demo);

create table product_variants (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references organisations(id) on delete cascade,
  product_id   uuid not null references products(id) on delete cascade,
  sku          text not null,
  title        text not null,
  options      jsonb not null default '{}'::jsonb,  -- {"size":"M","colour":"black"}
  weight_grams int,
  is_active    boolean not null default true,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (org_id, sku)
);

create index product_variants_product_idx on product_variants(product_id);

-- -----------------------------------------------------------------------------
-- Identifiers (§17)
-- -----------------------------------------------------------------------------
-- GTINs are NEVER generated by this system. `source` records where each one
-- came from so an invented value cannot masquerade as a legitimate one, and
-- `verified_at` records when a human or an API last confirmed it.

create type identifier_type as enum ('sku', 'upc', 'ean', 'gtin', 'isbn', 'asin', 'mpn', 'supplier_sku');
create type identifier_source as enum ('manufacturer', 'supplier', 'gs1', 'marketplace', 'owner_supplied', 'gtin_exemption');

create table product_identifiers (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references organisations(id) on delete cascade,
  product_id  uuid not null references products(id) on delete cascade,
  variant_id  uuid references product_variants(id) on delete cascade,

  id_type     identifier_type not null,
  value       text not null,
  source      identifier_source not null,
  evidence    text,                       -- where it came from, in words
  verified_at timestamptz,
  verified_by uuid references auth.users(id),

  created_at  timestamptz not null default now(),
  unique (org_id, id_type, value)
);

create index product_identifiers_product_idx on product_identifiers(product_id);

-- -----------------------------------------------------------------------------
-- Research and opportunity scoring (§7, §8, §9, §10)
-- -----------------------------------------------------------------------------

create type research_source as enum (
  'google_trends', 'amazon_api', 'shopify_api', 'tiktok_api',
  'supplier_catalogue', 'licensed_dataset', 'manual', 'demo'
);

create table product_research (
  id           uuid primary key default gen_random_uuid(),
  org_id       uuid not null references organisations(id) on delete cascade,
  product_id   uuid references products(id) on delete set null,

  candidate_title text not null,
  category        text,
  source          research_source not null,
  source_reference text,               -- API id / dataset row, for traceability
  collected_at    timestamptz not null default now(),

  raw_signals  jsonb not null default '{}'::jsonb,
  complaints   jsonb not null default '[]'::jsonb,  -- §10 extracted complaint themes
  differentiation jsonb not null default '[]'::jsonb, -- §11 original ideas only
  notes        text,
  is_demo      boolean not null default false
);

create index product_research_org_idx on product_research(org_id, collected_at desc);

-- Scores are versioned, never overwritten, so a decision can be replayed
-- against the inputs that actually produced it.
create table product_scores (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references organisations(id) on delete cascade,
  product_id  uuid references products(id) on delete cascade,
  research_id uuid references product_research(id) on delete cascade,

  total_score  int not null check (total_score between 0 and 100),
  band         text not null,          -- exceptional | strong | test | watch | reject
  components   jsonb not null,         -- every sub-score with its weight
  weights_version text not null,
  rationale    text,

  scored_at   timestamptz not null default now(),

  constraint score_has_subject check (product_id is not null or research_id is not null)
);

create index product_scores_product_idx on product_scores(product_id, scored_at desc);

-- -----------------------------------------------------------------------------
-- Generated listing content (§18) — original content only
-- -----------------------------------------------------------------------------

create table product_content (
  id          uuid primary key default gen_random_uuid(),
  org_id      uuid not null references organisations(id) on delete cascade,
  product_id  uuid not null references products(id) on delete cascade,
  channel     text not null,           -- 'shopify' | 'amazon' | 'shared'

  title            text,
  description      text,
  bullets          text[],
  features         text[],
  faqs             jsonb not null default '[]'::jsonb,
  seo_title        text,
  meta_description text,
  keywords         text[],
  image_brief      text,
  positioning      text,

  generated_by  text,                  -- model id, or 'human'
  approved_at   timestamptz,
  approved_by   uuid references auth.users(id),
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (org_id, product_id, channel)
);

create trigger products_touch before update on products
  for each row execute function touch_updated_at();
create trigger product_variants_touch before update on product_variants
  for each row execute function touch_updated_at();
create trigger product_content_touch before update on product_content
  for each row execute function touch_updated_at();
